# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
matrix:
  include:
    - python: 2.7
      env: USE_CHROOT=1
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  - pip install nose
  # pip install coverage
  - python -V
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
  - popd

install:
  # We used to use 'setup.py install' here, but that has the terrible
  # behaviour that if a copy of the package is already installed in
  # the install location, then the new copy just gets dropped on top
  # of it. Travis typically has a stable numpy release pre-installed,
  # and if we don't remove it, then we can accidentally end up
  # e.g. running old test modules that were in the stable release but
  # have been removed from master. (See gh-2765, gh-2768.)  Using 'pip
  # install' also has the advantage that it tests that numpy is 'pip
  # install' compatible, see e.g. gh-2766...
  - if [ "${USE_BENTO}" == "1" ]; then source .bento_travisci.sh; elif [ "${USE_CHROOT}" != "1" ]; then pip install .; fi
script:
  # We change directories to make sure that python won't find the copy
  # of numpy in the source directory.
  - if [ "${USE_CHROOT}" == "1" ]; then ./.travis.sh && exit 0; exit 1; fi
