# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
cache:
  directories:
    - $HOME/npy_ccache
sudo: false
python:
  - 2.7
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  - pip install nose
  # pip install coverage
  - python -V
  - pip install --upgrade pip setuptools
  # Speed up install by not compiling Cython
  - pip install --install-option="--no-cython-compile" Cython
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran ccache
  - popd

script:
  - ./tools/travis-test.sh
