
/*
 *****************************************************************************
 **       This file was autogenerated from a template  DO NOT EDIT!!!!      **
 **       Changes should be made to the original source (.src) file         **
 *****************************************************************************
 */

#line 1
/*
 *****************************************************************************
 **               IMPORTANT NOTE for npy_partition.h.src -> npy_partition.h **
 *****************************************************************************
 *  The template file loops.h.src is not automatically converted into
 *  loops.h by the build system.  If you edit this file, you must manually
 *  do the conversion using numpy/distutils/conv_template.py from the
 *  command line as follows:
 *
 *  $ cd <NumPy source root directory>
 *  $ python  numpy/distutils/conv_template.py numpy/core/src/private/npy_partition.h.src
 *  $
 */


#ifndef __NPY_PARTITION_H__
#define __NPY_PARTITION_H__


#include "npy_sort.h"

/* Python include is for future object sorts */
#include <Python.h>
#include <numpy/npy_common.h>
#include <numpy/ndarraytypes.h>

#define NPY_ENOMEM 1
#define NPY_ECOMP 2




#line 46

int quickselect_bool(npy_bool *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_bool(npy_bool *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_bool(npy_bool *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_bool(npy_bool *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_byte(npy_byte *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_byte(npy_byte *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_byte(npy_byte *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_byte(npy_byte *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_ubyte(npy_ubyte *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_ubyte(npy_ubyte *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_ubyte(npy_ubyte *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_ubyte(npy_ubyte *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_short(npy_short *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_short(npy_short *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_short(npy_short *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_short(npy_short *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_ushort(npy_ushort *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_ushort(npy_ushort *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_ushort(npy_ushort *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_ushort(npy_ushort *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_int(npy_int *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_int(npy_int *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_int(npy_int *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_int(npy_int *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_uint(npy_uint *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_uint(npy_uint *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_uint(npy_uint *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_uint(npy_uint *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_long(npy_long *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_long(npy_long *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_long(npy_long *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_long(npy_long *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_ulong(npy_ulong *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_ulong(npy_ulong *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_ulong(npy_ulong *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_ulong(npy_ulong *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_longlong(npy_longlong *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_longlong(npy_longlong *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_longlong(npy_longlong *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_longlong(npy_longlong *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_ulonglong(npy_ulonglong *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_ulonglong(npy_ulonglong *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_ulonglong(npy_ulonglong *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_ulonglong(npy_ulonglong *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_half(npy_ushort *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_half(npy_ushort *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_half(npy_ushort *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_half(npy_ushort *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_float(npy_float *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_float(npy_float *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_float(npy_float *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_float(npy_float *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_double(npy_double *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_double(npy_double *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_double(npy_double *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_double(npy_double *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_longdouble(npy_longdouble *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_longdouble(npy_longdouble *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_longdouble(npy_longdouble *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_longdouble(npy_longdouble *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_cfloat(npy_cfloat *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_cfloat(npy_cfloat *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_cfloat(npy_cfloat *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_cfloat(npy_cfloat *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_cdouble(npy_cdouble *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_cdouble(npy_cdouble *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_cdouble(npy_cdouble *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_cdouble(npy_cdouble *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);



#line 46

int quickselect_clongdouble(npy_clongdouble *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_clongdouble(npy_clongdouble *v, npy_intp* tosort, npy_intp num,
                        npy_intp kth, void *NOT_USED);

int quickselect_mom_clongdouble(npy_clongdouble *v, npy_intp num, npy_intp kth, void *NOT_USED);
int aquickselect_mom_clongdouble(npy_clongdouble *v, npy_intp* tosort, npy_intp num,
                            npy_intp kth, void *NOT_USED);




int quickselect_string(npy_char *vec, npy_intp cnt, PyArrayObject *arr);
int aquickselect_string(npy_char *vec, npy_intp *ind, npy_intp cnt, npy_intp kth, void *null);


int quickselect_unicode(npy_ucs4 *vec, npy_intp cnt, PyArrayObject *arr);
int aquickselect_unicode(npy_ucs4 *vec, npy_intp *ind, npy_intp cnt, npy_intp kth, void *null);

typedef struct {
    enum NPY_TYPES typenum;
    PyArray_PartitionFunc * part[NPY_NSELECTS];
    PyArray_ArgPartitionFunc * argpart[NPY_NSELECTS];
} part_map;

static part_map _part_map[] = {
#line 85
    {
        NPY_BOOL,
        {
            (PyArray_PartitionFunc *)&quickselect_bool,
            (PyArray_PartitionFunc *)&quickselect_mom_bool
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_bool,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_bool
        }
    },

#line 85
    {
        NPY_BYTE,
        {
            (PyArray_PartitionFunc *)&quickselect_byte,
            (PyArray_PartitionFunc *)&quickselect_mom_byte
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_byte,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_byte
        }
    },

#line 85
    {
        NPY_UBYTE,
        {
            (PyArray_PartitionFunc *)&quickselect_ubyte,
            (PyArray_PartitionFunc *)&quickselect_mom_ubyte
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_ubyte,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_ubyte
        }
    },

#line 85
    {
        NPY_SHORT,
        {
            (PyArray_PartitionFunc *)&quickselect_short,
            (PyArray_PartitionFunc *)&quickselect_mom_short
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_short,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_short
        }
    },

#line 85
    {
        NPY_USHORT,
        {
            (PyArray_PartitionFunc *)&quickselect_ushort,
            (PyArray_PartitionFunc *)&quickselect_mom_ushort
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_ushort,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_ushort
        }
    },

#line 85
    {
        NPY_INT,
        {
            (PyArray_PartitionFunc *)&quickselect_int,
            (PyArray_PartitionFunc *)&quickselect_mom_int
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_int,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_int
        }
    },

#line 85
    {
        NPY_UINT,
        {
            (PyArray_PartitionFunc *)&quickselect_uint,
            (PyArray_PartitionFunc *)&quickselect_mom_uint
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_uint,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_uint
        }
    },

#line 85
    {
        NPY_LONG,
        {
            (PyArray_PartitionFunc *)&quickselect_long,
            (PyArray_PartitionFunc *)&quickselect_mom_long
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_long,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_long
        }
    },

#line 85
    {
        NPY_ULONG,
        {
            (PyArray_PartitionFunc *)&quickselect_ulong,
            (PyArray_PartitionFunc *)&quickselect_mom_ulong
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_ulong,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_ulong
        }
    },

#line 85
    {
        NPY_LONGLONG,
        {
            (PyArray_PartitionFunc *)&quickselect_longlong,
            (PyArray_PartitionFunc *)&quickselect_mom_longlong
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_longlong,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_longlong
        }
    },

#line 85
    {
        NPY_ULONGLONG,
        {
            (PyArray_PartitionFunc *)&quickselect_ulonglong,
            (PyArray_PartitionFunc *)&quickselect_mom_ulonglong
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_ulonglong,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_ulonglong
        }
    },

#line 85
    {
        NPY_HALF,
        {
            (PyArray_PartitionFunc *)&quickselect_half,
            (PyArray_PartitionFunc *)&quickselect_mom_half
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_half,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_half
        }
    },

#line 85
    {
        NPY_FLOAT,
        {
            (PyArray_PartitionFunc *)&quickselect_float,
            (PyArray_PartitionFunc *)&quickselect_mom_float
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_float,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_float
        }
    },

#line 85
    {
        NPY_DOUBLE,
        {
            (PyArray_PartitionFunc *)&quickselect_double,
            (PyArray_PartitionFunc *)&quickselect_mom_double
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_double,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_double
        }
    },

#line 85
    {
        NPY_LONGDOUBLE,
        {
            (PyArray_PartitionFunc *)&quickselect_longdouble,
            (PyArray_PartitionFunc *)&quickselect_mom_longdouble
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_longdouble,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_longdouble
        }
    },

#line 85
    {
        NPY_CFLOAT,
        {
            (PyArray_PartitionFunc *)&quickselect_cfloat,
            (PyArray_PartitionFunc *)&quickselect_mom_cfloat
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_cfloat,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_cfloat
        }
    },

#line 85
    {
        NPY_CDOUBLE,
        {
            (PyArray_PartitionFunc *)&quickselect_cdouble,
            (PyArray_PartitionFunc *)&quickselect_mom_cdouble
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_cdouble,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_cdouble
        }
    },

#line 85
    {
        NPY_CLONGDOUBLE,
        {
            (PyArray_PartitionFunc *)&quickselect_clongdouble,
            (PyArray_PartitionFunc *)&quickselect_mom_clongdouble
        },
        {
            (PyArray_ArgPartitionFunc *)&aquickselect_clongdouble,
            (PyArray_ArgPartitionFunc *)&aquickselect_mom_clongdouble
        }
    },

};


static NPY_NO_EXPORT PyArray_PartitionFunc *
get_partition_func(int type, NPY_SELECTKIND which)
{
    npy_intp i;
    if (which >= NPY_NSELECTS)
        return NULL;
    for (i = 0; i < sizeof(_part_map)/sizeof(_part_map[0]); i++) {
        if (type == _part_map[i].typenum) {
            return _part_map[i].part[which];
        }
    }
    return NULL;
}


static NPY_NO_EXPORT PyArray_ArgPartitionFunc *
get_argpartition_func(int type, NPY_SELECTKIND which)
{
    npy_intp i;
    if (which >= NPY_NSELECTS)
        return NULL;
    for (i = 0; i < sizeof(_part_map)/sizeof(_part_map[0]); i++) {
        if (type == _part_map[i].typenum) {
            return _part_map[i].argpart[which];
        }
    }
    return NULL;
}

#endif

